import './globals.css'
import { Open_Sans } from 'next/font/google'
import Navbar from '@/components/Navbar'
import AuthContext from '@/context/AuthContext'

const sans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={sans.className}>
      <body className='w-full max-w-screen-xl m-auto overflow-auto'>
        <AuthContext>
          <header className='sticky top-0 bg-white z-10 border-b-2 border-gray-200'>
            <Navbar />
          </header>
          <main className='grow'>{children}</main>
        </AuthContext>
      </body>
    </html>
  )
}
